//try catch
const numero1 = 10;
const numero3 = 15;

console.log(numero1);

try {
    console.log(numero2);
} catch (error) {
    console.log(error)
}

console.log(numero3);0.